// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package nl.hanze.web.rmi;

public final class HelloImpl_Stub
    extends java.rmi.server.RemoteStub
    implements nl.hanze.web.rmi.Hello, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_ageNextYear_0;
    private static java.lang.reflect.Method $method_sayHello_1;
    private static java.lang.reflect.Method $method_sayHello_2;
    private static java.lang.reflect.Method $method_sayHello_3;
    private static java.lang.reflect.Method $method_sayHello_4;
    
    static {
	try {
	    $method_ageNextYear_0 = nl.hanze.web.rmi.Hello.class.getMethod("ageNextYear", new java.lang.Class[] {int.class});
	    $method_sayHello_1 = nl.hanze.web.rmi.Hello.class.getMethod("sayHello", new java.lang.Class[] {});
	    $method_sayHello_2 = nl.hanze.web.rmi.Hello.class.getMethod("sayHello", new java.lang.Class[] {int.class});
	    $method_sayHello_3 = nl.hanze.web.rmi.Hello.class.getMethod("sayHello", new java.lang.Class[] {java.lang.String.class});
	    $method_sayHello_4 = nl.hanze.web.rmi.Hello.class.getMethod("sayHello", new java.lang.Class[] {java.lang.String.class, int.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public HelloImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of ageNextYear(int)
    public int ageNextYear(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_ageNextYear_0, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -1292714532152859216L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of sayHello()
    public java.lang.String sayHello()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_sayHello_1, null, 6043973830760146143L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of sayHello(int)
    public java.lang.String sayHello(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_sayHello_2, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -4982402400161927182L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of sayHello(String)
    public java.lang.String sayHello(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_sayHello_3, new java.lang.Object[] {$param_String_1}, 8370655165776887524L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of sayHello(String, int)
    public java.lang.String sayHello(java.lang.String $param_String_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_sayHello_4, new java.lang.Object[] {$param_String_1, new java.lang.Integer($param_int_2)}, 7404776958654036967L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
